export const BaseVariable = Object.assign({
    BaseUri: "http://127.0.0.1:89/xxx/",
    COMM_FLD_VALUE_DBID: "01",
    MQTT_SERVICE : 'ws://127.0.0.1:85/ws',
    MQTT_USERNAME:'bipmq',
    MQTT_PASSWORD:'bipmq',
    MQTT_HOST:'bipmq',
    Project_Name:'',
    COPYRIGHT:"",
    SMSURL : "",
    ITEMTYPE:"",
    AouthTokenUrl:"",
    UniteLoginUrl:"",
    SKIN:"",
  });